# Generated by Django 5.2.5 on 2025-08-17 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('mailwatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_user_msgid_source',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='mailwatch_n_user_id_3b1152_idx',
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together={('user', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'application', 'external_message_id')},
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google / Gmail'), ('microsoft', 'Microsoft / Outlook')], max_length=32),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailwatch_notifications', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'external_message_id'], name='mailwatch_n_user_id_fccd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='mailwatch_n_user_id_90f6ef_idx'),
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='matched_via',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread_id',
        ),
    ]
