# fly.toml app configuration file generated for grad-app on 2025-08-16T21:35:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grad-app'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "sh -lc \"python manage.py migrate && python manage.py collectstatic --noinput\""

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 40
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '120s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
