# fly.toml for Django on Fly
app = "grad-app"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[deploy]
  # Run migrations + collect static on each deploy
  release_command = "sh -lc 'python manage.py migrate && python manage.py collectstatic --noinput'"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 40
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "120s"
    method = "GET"
    path = "/healthz"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1